In [3]:
import pandas as pd

# Define the column names
columns = ['Number of Fireplaces', 'Other Perils', 'Fire', 'Other Wind and Hail', 'Theft', 'Water',
           'Liability', 'Hurricane', 'Severe Thunderstorm', 'Winter Storm', 'Earthquake']

# Define the data
data = [
    [0, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    [1, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    [2, 1.0000, 1.0000, 1.0000, 1.1220, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    ['3+', 1.0000, 1.0000, 1.0000, 1.1220, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=columns)

# Display the DataFrame
df

,Number of Fireplaces,Other Perils,Fire,Other Wind and Hail,Theft,Water,Liability,Hurricane,Severe Thunderstorm,Winter Storm,Earthquake
0,0,1.0,1.0,1.0,1.000,1.0,1.0,1.0,1.0,1.0,1.0
1,1,1.0,1.0,1.0,1.000,1.0,1.0,1.0,1.0,1.0,1.0
2,2,1.0,1.0,1.0,1.122,1.0,1.0,1.0,1.0,1.0,1.0
3,3+,1.0,1.0,1.0,1.122,1.0,1.0,1.0,1.0,1.0,1.0

In [4]:
df.to_csv("D:\\LSU\\Research\\wind_ins\\USAA-134022151\\output_tables\\Owner\\34_num_fireplaces.csv", index=False)