In [2]:
import PyPDF2
import re
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)
# Function to extract specific lines from a given page number
def extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line):
    with open(pdf_path, 'rb') as file:
        # Create a PDF reader object
        pdf_reader = PyPDF2.PdfReader(file)
        
        # Check if the page number is within the range
        if page_number < len(pdf_reader.pages):
            # Extract text from the specific page
            page = pdf_reader.pages[page_number]
            text = page.extract_text()
            
            # Split the text into lines
            lines = text.split('\n')
            
            # Get the desired lines (adjusting for zero-based indexing)
            if len(lines) >= end_line:
                return lines[start_line-1:end_line]
            else:
                return "Page does not contain enough lines."
        else:
            return "Page number is out of range."


def convert_to_numeric(input_list):
    numeric_list = []
    for item in input_list:
        try:
            numeric_list.append(float(item))  # Attempt to convert to float
        except ValueError:
            continue  # Skip if conversion fails
    return numeric_list


def adjust_large_values(arr):
    arr[arr > 1000] = arr[arr > 1000] / 10000
    return arr

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 341
start_line = 12
end_line = 28
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 8))

data_values_1 = pd.DataFrame(data_values)

data_values_1

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 342
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 8))

data_values_2 = pd.DataFrame(data_values)

data_values_2

In [ ]:
data_values_2 = pd.concat([data_values_1, data_values_2], ignore_index=True)
data_values_2.columns = ['Amount of Insurance', '$500', '$1000', '$2000', '$5000', '$10000', '1%', '2%']
data_values_2

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 343
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 5))

data_values_3 = pd.DataFrame(data_values)

data_values_3.columns = [ 'Amount of Insurance','1%', '2%', '3%', '5%']
data_values_3

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 344
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 8))

data_values_4 = pd.DataFrame(data_values)

data_values_4.columns = ['Amount of Insurance', '$500', '$1000', '$2000', '$5000', '$10000', '1%', '2%']
data_values_4

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 345
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 8))

data_values_5 = pd.DataFrame(data_values)

data_values_5.columns = ['Amount of Insurance', '$500', '$1000', '$2000', '$5000', '$10000', '1%', '2%']
data_values_5

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 346
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 8))

data_values_6 = pd.DataFrame(data_values)

data_values_6.columns = ['Amount of Insurance', '$500', '$1000', '$2000', '$5000', '$10000', '1%', '2%']
data_values_6

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 347
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 5))

data_values_7 = pd.DataFrame(data_values)

data_values_7.columns = [ 'Amount of Insurance','1%', '2%', '3%', '5%']
data_values_7

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 348
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 5))

data_values_8 = pd.DataFrame(data_values)

data_values_8.columns = [ 'Amount of Insurance','1%', '2%', '3%', '5%']
data_values_8

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 349
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 5))

data_values_9 = pd.DataFrame(data_values)

data_values_9.columns = [ 'Amount of Insurance','1%', '2%', '3%', '5%']
data_values_9

In [ ]:
pdf_path = 'D:\\homeowner_insurance_USAA\\LA Rate Pages - Part 1.pdf'  
page_number = 350
start_line = 11
end_line = 27
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = np.array(data_values)

data_values = np.reshape(data_values, (-1, 2))

data_values_10 = pd.DataFrame(data_values)

data_values_10.columns = [ 'Amount of Insurance','10%']
data_values_10

In [31]:
amount_of_insurance_table = pd.DataFrame()
amount_of_insurance_table = pd.concat([data_values_2, data_values_3, data_values_4, data_values_5, data_values_6, data_values_7, data_values_8, data_values_9, data_values_10], ignore_index= True)
amount_of_insurance_table = amount_of_insurance_table.fillna('')
amount_of_insurance_table

,Amount of Insurance,$500,$1000,$2000,$5000,$10000,1%,2%,3%,5%,10%
0,"$10,000",0.1502,0.1345,0.1263,0.1212,0.1195,0.2443,0.1916,,,
1,"$50,000",0.5209,0.4085,0.3363,0.2868,0.2693,0.5209,0.4085,,,
2,"$100,000",0.9204,0.7217,0.5660,0.4439,0.3974,0.7217,0.5660,,,
3,"$150,000",1.2612,1.0088,0.7877,0.5899,0.5094,0.8734,0.6849,,,
4,"$200,000",1.5489,1.2752,1.0000,0.7316,0.6150,1.0000,0.7842,,,
...,...,...,...,...,...,...,...,...,...,...,...
165,"$750,000",,,,,,,,,,3.7057
166,"$1,000,000",,,,,,,,,,4.9282
167,"$1,500,000",,,,,,,,,,7.3653
168,"$2,000,000",,,,,,,,,,9.7951
169,"$3,000,000",,,,,,,,,,14.6391

In [32]:
perils = [
    'Other Perils', 'Fire', 'Other Wind and Hail', 'Theft', 'Water', 
    'Liability', 'Hurricane', 'Severe Thunderstorm', 'Winter Storm', 'Earthquake'
]

repeated_perils = [peril for peril in perils for _ in range(17)]
Peril = pd.DataFrame({'Peril': repeated_perils})

In [33]:
amount_of_insurance_table = pd.concat([Peril, amount_of_insurance_table], axis=1, ignore_index= True)

amount_of_insurance_table

,0,1,2,3,4,5,6,7,8,9,10,11
0,Other Perils,"$10,000",0.1502,0.1345,0.1263,0.1212,0.1195,0.2443,0.1916,,,
1,Other Perils,"$50,000",0.5209,0.4085,0.3363,0.2868,0.2693,0.5209,0.4085,,,
2,Other Perils,"$100,000",0.9204,0.7217,0.5660,0.4439,0.3974,0.7217,0.5660,,,
3,Other Perils,"$150,000",1.2612,1.0088,0.7877,0.5899,0.5094,0.8734,0.6849,,,
4,Other Perils,"$200,000",1.5489,1.2752,1.0000,0.7316,0.6150,1.0000,0.7842,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
165,Earthquake,"$750,000",,,,,,,,,,3.7057
166,Earthquake,"$1,000,000",,,,,,,,,,4.9282
167,Earthquake,"$1,500,000",,,,,,,,,,7.3653
168,Earthquake,"$2,000,000",,,,,,,,,,9.7951
169,Earthquake,"$3,000,000",,,,,,,,,,14.6391

In [34]:
amount_of_insurance_table.columns = ['Peril', 'Amount of Insurance', '$500', '$1000', '$2000', '$5000', '$10000', '1%', '2%', '3%', '5%', '10%' ]

In [35]:
amount_of_insurance_table

,Peril,Amount of Insurance,$500,$1000,$2000,$5000,$10000,1%,2%,3%,5%,10%
0,Other Perils,"$10,000",0.1502,0.1345,0.1263,0.1212,0.1195,0.2443,0.1916,,,
1,Other Perils,"$50,000",0.5209,0.4085,0.3363,0.2868,0.2693,0.5209,0.4085,,,
2,Other Perils,"$100,000",0.9204,0.7217,0.5660,0.4439,0.3974,0.7217,0.5660,,,
3,Other Perils,"$150,000",1.2612,1.0088,0.7877,0.5899,0.5094,0.8734,0.6849,,,
4,Other Perils,"$200,000",1.5489,1.2752,1.0000,0.7316,0.6150,1.0000,0.7842,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
165,Earthquake,"$750,000",,,,,,,,,,3.7057
166,Earthquake,"$1,000,000",,,,,,,,,,4.9282
167,Earthquake,"$1,500,000",,,,,,,,,,7.3653
168,Earthquake,"$2,000,000",,,,,,,,,,9.7951
169,Earthquake,"$3,000,000",,,,,,,,,,14.6391

In [36]:
amount_of_insurance_table.to_csv("D:\\homeowner_insurance_USAA\\8_amount_of_insurance_factor.csv", index=False)