In [30]:
import PyPDF2
import re
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)
# Function to extract specific lines from a given page number
def extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line):
    with open(pdf_path, 'rb') as file:
        # Create a PDF reader object
        pdf_reader = PyPDF2.PdfReader(file)
        
        # Check if the page number is within the range
        if page_number < len(pdf_reader.pages):
            # Extract text from the specific page
            page = pdf_reader.pages[page_number]
            text = page.extract_text()
            
            # Split the text into lines
            lines = text.split('\n')
            
            # Get the desired lines (adjusting for zero-based indexing)
            if len(lines) >= end_line:
                return lines[start_line-1:end_line]
            else:
                return "Page does not contain enough lines."
        else:
            return "Page number is out of range."


def convert_to_numeric(input_list):
    numeric_list = []
    for item in input_list:
        try:
            numeric_list.append(float(item))  # Attempt to convert to float
        except ValueError:
            continue  # Skip if conversion fails
    return numeric_list


def adjust_large_values(arr):
    arr[arr > 1000] = arr[arr > 1000] / 10000
    return arr

In [35]:
pdf_path = 'D:\\LSU\\Research\\wind_ins\\USAA-134022151\\Rate-Rule Attachments\\LA Rate Pages - Part 1.pdf'  
page_number = 1
start_line = 14
end_line = 34
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = convert_to_numeric(data_values)

data_values = np.array(data_values)

data_values = data_values[data_values != 0]
data_values = adjust_large_values(data_values)
data_values = np.reshape(data_values, (-1, 12))

data_values_1 = pd.DataFrame(data_values)

data_values_1

,0,1,2,3,4,5,6,7,8,9,10,11
0,5.0000,0.2969,0.1491,0.5103,0.2288,0.3052,0.2261,1.0000,0.6629,1.0000,1.0000,0.2969
1,6.0000,0.3081,0.1579,0.5208,0.2393,0.3163,0.2365,1.0000,0.6712,1.0000,1.0000,0.3081
2,7.0000,0.3196,0.1673,0.5315,0.2502,0.3279,0.2474,1.0000,0.6796,1.0000,1.0000,0.3196
3,8.0000,0.3316,0.1772,0.5424,0.2616,0.3399,0.2588,1.0000,0.6881,1.0000,1.0000,0.3316
4,9.0000,0.3440,0.1878,0.5536,0.2736,0.3524,0.2707,1.0000,0.6968,1.0000,1.0000,0.3440
5,10.0000,0.3569,0.1989,0.5650,0.2861,0.3653,0.2832,1.0000,0.7055,1.0000,1.0000,0.3569
6,11.0000,0.3703,0.2107,0.5767,0.2992,0.3787,0.2962,1.0000,0.7143,1.0000,1.0000,0.3703
7,12.0000,0.3842,0.2232,0.5885,0.3128,0.3925,0.3099,1.0000,0.7233,1.0000,1.0000,0.3842
8,13.0000,0.3986,0.2365,0.6007,0.3271,0.4069,0.3242,1.0000,0.7324,1.0000,1.0000,0.3986
9,14.0000,0.4135,0.2505,0.6130,0.3421,0.4218,0.3391,1.0000,0.7415,1.0000,1.0000,0.4135
10,15.0000,0.4290,0.2654,0.6257,0.3577,0.4372,0.3548,1.0000,0.7508,1.0000,1.0000,0.4290
11,16.0000,0.4451,0.2811,0.6385,0.3741,0.4533,0.3711,1.0000,0.7603,1.0000,1.0000,0.4451
12,17.0000,0.4618,0.2978,0.6517,0.3912,0.4699,0.3882,1.0000,0.7698,1.0000,1.0000,0.4618
13,18.0000,0.4791,0.3155,0.6651,0.4091,0.4871,0.4061,1.0000,0.7794,1.0000,1.0000,0.4791
14,19.0000,0.4970,0.3343,0.6788,0.4278,0.5049,0.4248,1.0000,0.7892,1.0000,1.0000,0.4970
15,20.0000,0.5156,0.3541,0.6928,0.4473,0.5234,0.4444,1.0000,0.7991,1.0000,1.0000,0.5156
16,21.0000,0.5350,0.3751,0.7071,0.4678,0.5426,0.4649,1.0000,0.8091,1.0000,1.0000,0.5350
17,22.0000,0.5550,0.3974,0.7216,0.4891,0.5624,0.4863,1.0000,0.8193,1.0000,1.0000,0.5550
18,23.0000,0.5758,0.4210,0.7365,0.5115,0.5830,0.5087,1.0000,0.8295,1.0000,1.0000,0.5758
19,24.0000,0.5974,0.4460,0.7517,0.5349,0.6044,0.5322,1.0000,0.8399,1.0000,1.0000,0.5974
20,25.0000,0.6198,0.4725,0.7672,0.5593,0.6265,0.5567,1.0000,0.8505,1.0000,1.0000,0.6198

In [36]:
pdf_path = 'D:\\LSU\\Research\\wind_ins\\USAA-134022151\\Rate-Rule Attachments\\LA Rate Pages - Part 1.pdf'  
page_number = 2
start_line = 14
end_line = 34
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = convert_to_numeric(data_values)

data_values = np.array(data_values)

data_values = data_values[data_values != 0]
data_values = adjust_large_values(data_values)
data_values = np.reshape(data_values, (-1, 12))

data_values_2 = pd.DataFrame(data_values)

data_values_2

,0,1,2,3,4,5,6,7,8,9,10,11
0,26.0000,0.6430,0.5005,0.7830,0.5849,0.6495,0.5823,1.0000,0.8611,1.0000,1.0000,0.6430
1,27.0000,0.6671,0.5302,0.7991,0.6116,0.6732,0.6092,1.0000,0.8719,1.0000,1.0000,0.6671
2,28.0000,0.6921,0.5617,0.8156,0.6396,0.6979,0.6373,1.0000,0.8829,1.0000,1.0000,0.6921
3,29.0000,0.7181,0.5951,0.8324,0.6688,0.7235,0.6666,1.0000,0.8939,1.0000,1.0000,0.7181
4,30.0000,0.7450,0.6304,0.8495,0.6994,0.7500,0.6974,1.0000,0.9051,1.0000,1.0000,0.7450
5,31.0000,0.7729,0.6678,0.8670,0.7314,0.7774,0.7295,1.0000,0.9165,1.0000,1.0000,0.7729
6,32.0000,0.8019,0.7075,0.8849,0.7648,0.8059,0.7631,1.0000,0.9280,1.0000,1.0000,0.8019
7,33.0000,0.8320,0.7495,0.9031,0.7997,0.8354,0.7983,1.0000,0.9396,1.0000,1.0000,0.8320
8,34.0000,0.8631,0.7940,0.9217,0.8363,0.8660,0.8351,1.0000,0.9514,1.0000,1.0000,0.8631
9,35.0000,0.8955,0.8411,0.9407,0.8745,0.8977,0.8736,1.0000,0.9633,1.0000,1.0000,0.8955
10,36.0000,0.9291,0.8911,0.9600,0.9145,0.9306,0.9138,1.0000,0.9754,1.0000,1.0000,0.9291
11,37.0000,0.9639,0.9440,0.9798,0.9563,0.9647,0.9559,1.0000,0.9876,1.0000,1.0000,0.9639
12,38.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
13,39.0000,1.0375,1.0594,1.0206,1.0457,1.0366,1.0461,1.0000,1.0125,1.0000,1.0000,1.0375
14,40.0000,1.0764,1.1223,1.0416,1.0935,1.0746,1.0943,1.0000,1.0252,1.0000,1.0000,1.0764
15,41.0000,1.1167,1.1889,1.0631,1.1435,1.1139,1.1447,1.0000,1.0381,1.0000,1.0000,1.1167
16,42.0000,1.1586,1.2595,1.0850,1.1958,1.1547,1.1975,1.0000,1.0511,1.0000,1.0000,1.1586
17,43.0000,1.2020,1.3343,1.1073,1.2504,1.1970,1.2527,1.0000,1.0643,1.0000,1.0000,1.2020
18,44.0000,1.2470,1.4135,1.1301,1.3076,1.2409,1.3104,1.0000,1.0776,1.0000,1.0000,1.2470
19,45.0000,1.2938,1.4974,1.1534,1.3673,1.2863,1.3708,1.0000,1.0911,1.0000,1.0000,1.2938
20,46.0000,1.3423,1.5863,1.1772,1.4298,1.3334,1.4340,1.0000,1.1048,1.0000,1.0000,1.3423

In [37]:
pdf_path = 'D:\\LSU\\Research\\wind_ins\\USAA-134022151\\Rate-Rule Attachments\\LA Rate Pages - Part 1.pdf'  
page_number = 3
start_line = 14
end_line = 35
specific_lines = extract_specific_lines_from_page(pdf_path, page_number, start_line, end_line)

data_values = ' '.join(specific_lines).split()

data_values = convert_to_numeric(data_values)

data_values = np.array(data_values)

data_values = data_values[data_values != 0]
data_values = adjust_large_values(data_values)
data_values = np.reshape(data_values, (-1, 12))

data_values_3 = pd.DataFrame(data_values)

data_values_3

,0,1,2,3,4,5,6,7,8,9,10,11
0,47.0000,1.3926,1.6805,1.2014,1.4952,1.3822,1.5001,1.0000,1.1187,1.0000,1.0000,1.3926
1,48.0000,1.4448,1.7803,1.2262,1.5635,1.4329,1.5692,1.0000,1.1327,1.0000,1.0000,1.4448
2,49.0000,1.4989,1.8860,1.2514,1.6350,1.4853,1.6415,1.0000,1.1469,1.0000,1.0000,1.4989
3,50.0000,1.5551,1.9979,1.2772,1.7097,1.5397,1.7172,1.0000,1.1613,1.0000,1.0000,1.5551
4,51.0000,1.6134,2.1166,1.3035,1.7879,1.5961,1.7964,1.0000,1.1758,1.0000,1.0000,1.6134
5,52.0000,1.6739,2.2422,1.3304,1.8696,1.6546,1.8791,1.0000,1.1906,1.0000,1.0000,1.6739
6,53.0000,1.7366,2.3753,1.3578,1.9551,1.7152,1.9657,1.0000,1.2055,1.0000,1.0000,1.7366
7,54.0000,1.8017,2.5164,1.3857,2.0444,1.7780,2.0563,1.0000,1.2206,1.0000,1.0000,1.8017
8,55.0000,1.8692,2.6658,1.4143,2.1379,1.8431,2.1511,1.0000,1.2359,1.0000,1.0000,1.8692
9,56.0000,1.9393,2.8240,1.4434,2.2356,1.9106,2.2503,1.0000,1.2514,1.0000,1.0000,1.9393
10,57.0000,2.0120,2.9917,1.4731,2.3378,1.9806,2.3540,1.0000,1.2671,1.0000,1.0000,2.0120
11,58.0000,2.0874,3.1693,1.5035,2.4446,2.0531,2.4625,1.0000,1.2830,1.0000,1.0000,2.0874
12,59.0000,2.1657,3.3575,1.5344,2.5564,2.1283,2.5760,1.0000,1.2991,1.0000,1.0000,2.1657
13,60.0000,2.2468,3.5568,1.5661,2.6732,2.2062,2.6947,1.0000,1.3153,1.0000,1.0000,2.2468
14,61.0000,2.3310,3.7680,1.5983,2.7954,2.2870,2.8189,1.0000,1.3318,1.0000,1.0000,2.3310
15,62.0000,2.4184,3.9917,1.6312,2.9232,2.3708,2.9488,1.0000,1.3485,1.0000,1.0000,2.4184
16,63.0000,2.5091,4.2287,1.6648,3.0568,2.4576,3.0847,1.0000,1.3654,1.0000,1.0000,2.5091
17,64.0000,2.6031,4.4798,1.6991,3.1965,2.5476,3.2269,1.0000,1.3826,1.0000,1.0000,2.6031
18,65.0000,2.7007,4.7458,1.7341,3.3426,2.6409,3.3756,1.0000,1.3999,1.0000,1.0000,2.7007
19,66.0000,2.8019,5.0275,1.7698,3.4954,2.7376,3.5312,1.0000,1.4174,1.0000,1.0000,2.8019
20,67.0000,2.9069,5.3260,1.8063,3.6552,2.8379,3.6939,1.0000,1.4352,1.0000,1.0000,2.9069
21,68.0000,3.0159,5.6423,1.8435,3.8222,2.9418,3.8642,1.0000,1.4532,1.0000,1.0000,3.0159

In [38]:
tier_factor_table = pd.concat([data_values_1, data_values_2, data_values_3], ignore_index=True)
tier_factor_table.columns =  ['Tier', 'Other Perils', 'Fire', 'Other Wind and Hail', 'Theft', 'Water',
           'Liability', 'Hurricane', 'Severe Thunderstorm', 'Winter Storm', 'Earthquake', 'Other Optional Coverages']

tier_factor_table

,Tier,Other Perils,Fire,Other Wind and Hail,Theft,Water,Liability,Hurricane,Severe Thunderstorm,Winter Storm,Earthquake,Other Optional Coverages
0,5.0000,0.2969,0.1491,0.5103,0.2288,0.3052,0.2261,1.0000,0.6629,1.0000,1.0000,0.2969
1,6.0000,0.3081,0.1579,0.5208,0.2393,0.3163,0.2365,1.0000,0.6712,1.0000,1.0000,0.3081
2,7.0000,0.3196,0.1673,0.5315,0.2502,0.3279,0.2474,1.0000,0.6796,1.0000,1.0000,0.3196
3,8.0000,0.3316,0.1772,0.5424,0.2616,0.3399,0.2588,1.0000,0.6881,1.0000,1.0000,0.3316
4,9.0000,0.3440,0.1878,0.5536,0.2736,0.3524,0.2707,1.0000,0.6968,1.0000,1.0000,0.3440
...,...,...,...,...,...,...,...,...,...,...,...,...
59,64.0000,2.6031,4.4798,1.6991,3.1965,2.5476,3.2269,1.0000,1.3826,1.0000,1.0000,2.6031
60,65.0000,2.7007,4.7458,1.7341,3.3426,2.6409,3.3756,1.0000,1.3999,1.0000,1.0000,2.7007
61,66.0000,2.8019,5.0275,1.7698,3.4954,2.7376,3.5312,1.0000,1.4174,1.0000,1.0000,2.8019
62,67.0000,2.9069,5.3260,1.8063,3.6552,2.8379,3.6939,1.0000,1.4352,1.0000,1.0000,2.9069
63,68.0000,3.0159,5.6423,1.8435,3.8222,2.9418,3.8642,1.0000,1.4532,1.0000,1.0000,3.0159

In [39]:
tier_factor_table.to_csv("D:\\LSU\\Research\\wind_ins\\USAA-134022151\\output_tables\\Owner\\7_tier_factor.csv", index=False)